version: 1
services:
  - type: web
    name: lung-cancer-detection
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python manage.py runserver 0.0.0.0:10000"
    healthCheckPath: "/"
    healthCheckInterval: 30000  
    healthCheckTimeout: 5000     # 5 seconds
    healthCheckSuccessThreshold: 2
    healthCheckFailureThreshold: 3
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: lung_cancer_detection.settings  # Make sure this matches your settings module path
